### ISSUE TITLE
doc: Highlighted source washes out the syntax highlighting

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1323]
Example:

http://falcon.readthedocs.io/en/stable/_modules/falcon/redirects.html#HTTPPermanentRedirect

**Comment by foresmac** [comment]
try adding the following line to `custom.css`:
```css
div.viewcode-block:target {
    background: #666;
}
```
`#333` Also works well, if you want more contrast between background and text, but it's harder to see that a particular block is highlighted.
